title: OpenVDM Documentation
email: info@oceandatatools.org
description: >-
  OpenVDM is a ship-wide data management platform for research vessels.
  It retrieves and organizes data from multiple instrument and data-acquisition
  systems into a unified cruise data package with web-based access and a
  plugin architecture for custom data processing.
github_username: oceandatatools
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages
  - _docs

exclude:
  - _docs/wip-*

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  bio: "OpenVDM is a ship-wide data management platform for research vessels."

atom_feed:
  hide: true

footer:
  links:
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://www.oceandatatools.org"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OceanDataTools/openvdm"
    - label: "MIT Open Source License"
      icon: "fas fa-file-alt"
      url: "https://opensource.org/license/mit"

defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "navdocs"

  - scope:
      path: ""
      type: pages
    values:
      layout: home
      author_profile: true
      sidebar:
        nav: "navdocs"

toc: true
toc_label: "Table of Contents"
toc_icon: "list"
toc_levels: "1..4"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  docs:
    output: true
    permalink: /:collection/:name
